force-app/main/default/objects/Boat__c/Boat__c.object-meta.xml
<CustomObject>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BoatReview__c/BoatReview__c.object-meta.xml
<CustomObject>
    <label>BoatReview</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BoatReview__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <label>Boat</label>
    <referenceTo>Boat__c</referenceTo>
    <relationshipLabel>Boat Reviews</relationshipLabel>
    <relationshipName>Boat_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BoatReview__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/BoatReviews.cls
public class BoatReviews {

    @AuraEnabled
    public static ID saveReview(BoatReview__c review) {
        insert review;
        return review.Id;
    }
	
    @AuraEnabled
    public static List<BoatReview__c> getAll(ID boatId) {
        return [select Id,Name,Comment__c,Rating__c,LastModifiedDate,CreatedDate,CreatedBy.Name,CreatedBy.SmallPhotoUrl,CreatedBy.CompanyName from BoatReview__c where Boat__c = :boatId];
    }
}