force-app/main/default/objects/Boat__c/Boat__c.object-meta.xml
<CustomObject>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boat__c/fields/BoatType__c.field-meta.xml
<CustomField>
    <fullName>BoatType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boat Type</label>
    <referenceTo>BoatType__c</referenceTo>
    <relationshipLabel>Boats</relationshipLabel>
    <relationshipName>Boats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boat__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Boats</relationshipLabel>
    <relationshipName>Boats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boat__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <inlineHelpText>In feet</inlineHelpText>
    <label>Length</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boat__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Estimated Pric</inlineHelpText>
    <label>Price</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BoatType__c/BoatType__c.object-meta.xml
<CustomObject>
    <label>Boat Type</label>
    <nameField>
        <label>Boat Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BoatSearchResults.cls
public class BoatSearchResults {
    
    @AuraEnabled
    public static List<Boat__c> getBoats(String boatTypeId) {
        if(String.isNotBlank(boatTypeId)) {
            return [select Id,Name,Contact__r.Name,Picture__c,BoatType__c,Geolocation__latitude__s,Geolocation__longitude__s from Boat__c where BoatType__c = :boatTypeId];
        }
        return [select Id,Name,Contact__r.Name,Picture__c,BoatType__c,Geolocation__latitude__s,Geolocation__longitude__s from Boat__c];
    }

    @AuraEnabled
    public static Boat__c getBoatById(String boatId) {
        return [select Id,Name,Description__c,Price__c,Length__c,Contact__r.Name,Contact__r.Email,Contact__r.HomePhone,BoatType__r.Name,Picture__c from Boat__c where Id = :boatId];
    }
}